### ISSUE TITLE
Use of undeclared type 'YUTableView' compiler error

### ISSUE THREAD

**Issue by bakomchik** [ujell/YUTableView-Swift#1]
Hi, first, i want to say you Thanks!
I faced with problem. I added `pod 'YUTableView-Swift'`  to my pod file. And  i import YUTableView_Swift
module  in my ViewController, 
I declared var
`@IBOutlet  var tableView:YUTableView!`

But i get compiler error `Use of undeclared type 'YUTableView' .`
Manual addidng files works fine

**Comment by ujell** [comment]
This is totally my bad, I just realized that I shouldn't have used "-" in the project name, it confuses cocoapods. I'll fix it as soon as possible.

**Comment by ujell** [comment]
Solved it, problem was actually access control. Should work after "pod update"
