### ISSUE TITLE
Support for swipe to delete?

### ISSUE THREAD

**Issue by thihaaung6245** [ujell/YUTableView-Swift#2]
Is there any feature support for Swipe to delete one of expanded cell,not the parent(title) cell?

I have been working to show the data with your YUTableView which was from the server.Like phone number editing.
Assume i got table structure like that

Dad - 08421111222
=>Child 1 - 0832122223(editable)/delete
=>Child 2 - 0632444433(editable)/delete

means dad share his phone data to his two child.If he don't want to share his data,he can delete.

Any Help?

**Comment by ujell** [comment]
I assumed you mean default table view behaviour of `commitEditingStyle` method in `UITableViewDataSource`. I haven't thought about it before so just made a quick implementation for now. Please check `canEditNode` and `didRemoveNode` methods in the `YUTableViewDelegate`. 

Although I'm aware this doesn't involve all necessary actions (like edit button) and I might also implement `editActionsForRowAtIndexPath` in the future.
