### ISSUE TITLE
Automatic height

### ISSUE THREAD

**Issue by tvstuff** [ujell/YUTableView-Swift#3]
Is there any way we can use nodes to have Automatic height according to their content
same as we do in height for tableview

**Comment by ujell** [comment]
Do you mean with `tableView.rowHeight = UITableViewAutomaticDimension` ? As long as you set row height to automatic and don't implement `heightForNode` it should work. Or am I missing something?

**Comment by ujell** [comment]
Can't reproduce and no reply in 2 months, so I'm closing this issue.
