### ISSUE TITLE
mytable.setNodes()

### ISSUE THREAD

**Issue by TaiPhamD** [ujell/YUTableView-Swift#5]
I am trying to change different set of nodes by using .setNodes. When I switch to the 2nd then switch back to the 1st set, it seems like there is some internal variables from the 2nd set that gets carried over back to the first set. It would crash and saying that the child node range is out of range.  Is setNodes() the right method for switching different set of nodes or should I try something else?

**Comment by ujell** [comment]
Just checked this and unfortunately I couldn't reproduce the error, it worked as expected for me. Can you give more information about your nodes and where exactly the error happened?

**Comment by TaiPhamD** [comment]
Ok let me try to create a standalone project that could reproduce the problem and upload it tonight.

**Comment by TaiPhamD** [comment]
https://github.com/interestingtome/YUTableTestRush
The UI will initially display data from the tableData. Then if you press the commit button after check marking some data items it will show data from tableData2. Pressing cancel will change the view back to tableData. As soon as I press cancel on the UI then trying to expand the nodes then I would get an error "fatal error: Array replace: subrange extends past the end at line 180 of the YUTableview.swift at the func closeNodeAtIndexRow.

**Comment by ujell** [comment]
I found the issue and pushed an update. Unfortunately right now I don't have AppStore version of the Xcode and CocoaPods is not allowing me to update the pod because of a bug. I'll do it as soon as possible, but till then you can simply change YUTableView.swift with the current one. 

Please let me know if it still crashes.

**Comment by TaiPhamD** [comment]
woohoo you fixed it. Thank you :)
